#ifndef ENUM_H
#define ENUM_H

typedef enum {
    APP_OK = 0,
    APP_REQUEST_FAILED,
    APP_INVALID_JSON,
    APP_INVALID_FORMAT,
    APP_API_FAILURE,
    APP_FAILED_TO_GET_DOWN_SPEED,
    APP_FAILED_TO_GET_UP_SPEED,

};

#endif